/*
 * Copyright 2006-2025 www.anyline.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.anyline.metadata;

import org.anyline.metadata.type.DatabaseType;

import java.util.List;

public interface SystemFunction {
    enum META{
        ABS("绝对值"),
        ACOS("弧余弦"),
        ADD_DATE("添加日期"),  //DATE_ADD
        ADD_TIME("添加时间"),  //TIME_ADD
        ALTER_LEVEL("修改级别全称名"),
        ALTER_POLICY("修改一个安全策略的策略选项"),
        ALTER_COMPARTMENT("修改安全隔间全称名"),
        ALTER_TABLE_CONTROL("修改表级控制属性"),
        ALTER_ROW_CONTROL("修改行级控制选项"),
        ALTER_COLUMN_CONTROL("修改列级控制"),
        ALTER_TAB_CONTROL_BASE_TIME("修改基于时间段的列集合访问控制时间间隔"),
        AES_DECRYPT("AES 解密"),
        AES_ENCRYPT("AES 加密"),
        ANY_VALUE(""),
        APPLY_TABLE_POLICY("应用安全策略到表"),
        APPLY_TABLE_CONTROL("应用表级控制"),
        APPLY_ROW_CONTROL("应用行级控制"),
        APPLY_COLUMN_CONTROL("应用列级控制"),
        APPLY_COLUMN_CONTROL_CONSTRAINT("应用列级控制推理约束"),
        ASCII("第一个字符的ASCII值"),
        ASIN("弧正弦"),
        ASYNCHRONOUS_CONNECTION_FAILOVER_ADD_MANAGED("将组成员源服务器配置信息添加到 复制通道源列表"),
        ASYNCHRONOUS_CONNECTION_FAILOVER_ADD_SOURCE("将源服务器配置信息服务器添加到 复制通道源列表"),
        ASYNCHRONOUS_CONNECTION_FAILOVER_DELETE_MANAGED("从复制通道源列表中删除托管组"),
        ASYNCHRONOUS_CONNECTION_FAILOVER_DELETE_SOURCE("从复制通道源列表中删除源服务器"),
        ASYNCHRONOUS_CONNECTION_FAILOVER_RESET("删除与异步组复制相关的所有设置 故障转移"),
        ATAN("圆弧切线"),
        ATAN2("两个参数的圆弧切线"),
        AVG("平均值"),
        BENCHMARK("重复执行表达式"),
        BETWEEN_AND("否在值范围内"),
        BINARY("包含数字二进制表示的字符串"),
        BINARY_TO_UUID("二进制 UUID 转换为字符串"),
        BINCHAR(""),
        STRING_TO_BINARY("字符串转换为二进制字符串"),
        BIT_AND("按位 AND"),
        BIT_COUNT("位数"),
        BIT_LENGTH("长度(以BIT为单位)"),
        BIT_OR("按位或"),
        BIT_XOR("按位异或"),
        CAN_ACCESS_COLUMN(""),
        CAN_ACCESS_DATABASE(""),
        CAN_ACCESS_TABLE(""),
        CAN_ACCESS_USER(""),
        CAN_ACCESS_VIEW(""),
        CASE("CASE WHEN"),
        CAST("值强制转换为特定类型"),
        CBRT("立方根"),
        CEIL("不小于参数的最小整数值"),
        CEILING("不小于参数的最小整数值", CEIL),
        CHAR("int转字符"),
        CHR("int转字符", CHAR),
        CHAR_LENGTH("字符数"),
        CHARACTER_LENGTH("字符数", CHAR_LENGTH),
        CHAR_INDEX("字符或者字符串在另一个字符串中的起始位置"),
        CHARSET("字符集"),
        COALESCE("第一个非 NULL值"),
        COERCIBILITY("字符串参数的排序规则强制性值"),
        COLLATION("字符串参数的排序规则"),
        COMPRESS("以二进制字符串的形式"),
        CONCAT("串联字符串"),
        CONCAT_WS("用分隔符连接字符串"), //concat_ws(',','11','22');  11,22
        CONNECTION_ID("当前连接ID"),
        CONVERT_NUMBER("不同进制(2-36)之间转换数字"),
        CONVERT("将值强制转换为特定类型"),
        CONVERT_TZ("从一个时区转换为另一个时区"),
        COS("余弦"),
        COT("余切"),
        COUNT("行数计数"),
        CRC32("循环冗余校验值"),
        CREATE_LEVEL("创建一个安全级别"),
        CREATE_POLICY("创建一个安全策略"),
        CREATE_COMPARTMENT("创建一个安全隔间"),
        CUME_DIST("累积分布概率"),
        CURRENT_DATE("当前日期"),
        CURRENT_ROLE("当前活动角色"),
        CURRENT_SETTING("查看某个参数值"),
        CURRENT_TIME("当前时间"),
        CURRENT_TIMESTAMP("当前时间戳"),
        CURRENT_DATABASE("数据库名称"),
        CURRENT_DATABASE_ID("当前连接的数据库 id"),
        CURRENT_SCHEMA("当前 schema"),
        CURRENT_SCHEMAS("schema 搜索路径"),
        CURRENT_SESSION_ID("显示当前用户的连接号"),
        CURRENT_USER("当前用户"),
        CURRENT_USER_ID("当前用户ID"),
        CURRVAL("序列值"),
        DATE("提取日期或日期时间表达式的日期部分"),
        DATE_ADD("将时间值（间隔）添加到日期值", ADD_DATE),
        DATE_DIFF("时间差"),
        DATE_MI("计算两个 DATE 值相差的天数"),
        DATE_FORMAT("按指定格式设置日期"),
        DATE_PLI("将指定的日期增加指定的天数", DATE_ADD),
        DATE_MII("将指定的日期减去指定的天数"),
        DATE_PART("获取给定日期的指定子域值"),
        DATE_SUB("从日期中减去时间值"),
        DATE_TRUNCATE("给定一个日期，截断成指定的精度"),
        DATE_SMALLER("最小日期"),
        DATE_LARGER("最大日期"),
        DAY_OF_MONTH("月份中的某一天"),
        DAY_NAME("工作日的名称"),
        DAY_OF_WEEK("工作日索引"),
        DAY_OF_WEEK_ISO("工作日索引"),
        DAY_OF_YEAR("一年中的某一天"),
        DAYS("得到指定日期与 0001 年 1 月 1 日的天数差值"),
        DECODING("将指定的字符串以特定的解码规则解码"),
        DEFAULT("表列的默认值"),
        DEGREES("弧度转换为度数"),
        DENSE_RANK("分区内当前行的排名"),
        DIFFERENCE("求两个字符串的读音相似性"),
        DIV("整数除法"),
        DROP_POLICY("删除一个安全策略"),
        DROP_LEVEL_BY_NAME("删除一个级别"),
        DROP_COMPARTMENT_BY_NAME("删除一个安全隔间"),
        DROP_TAB_CONTROL_BASE_TIME("删除基于时间段的列集合访问控制"),
        ELT("参数列表中指定位置的字符串"), //ELT(n, str1, str2, ..., strn) 返回第n个字符串
        EMPTY_BLOB("对 BLOB 定位符进行初始化"),
        EMPTY_CLOB("对 CLOB 定位符进行初始化"),
        ENABLE_POLICY("修改一个安全策略的可用状态"),
        ENABLE_TABLE_POLICY("修改策略应用状态"),
        ENCODING("将二进制串进行编码"), //ENCODING('0x1011', 'HEX');
        EXISTS("查询结果是否包含任何行"),
        EXP("自然对数的底数e的指定次幂"),
        EXPORT_SET("将整数转换为由指定字符串分隔的二进制位表示"),
        EXTRACT("获取子域"), //EXTRACT(DAY FROM TIMESTAMP '2001-02-16 20:38:40') > 16
        EXTRACT_DATE_PART("提取日期的一部分"), //EXTRACT(YEAR FROM '2025-11-15') AS year;
        EXTRACT_VALUE("使用 XPath 表示法从 XML 字符串中提取值"), //EXTRACTVALUE('<a><b>NAME</b></a>', '/a/b'); -- 返回 'NAME'
        FACTORIAL("阶乘"),
        FIELD("一个值(value)在给定列表(val1, val2, ...)中第一次出现的索引"), // INDEX OF
        FIND_IN_SET("第二个参数中第一个参数的索引"),
        FIRST_VALUE("第一行的参数值"),
        FLOOR("不大于参数的最大整数值"),
        FORMAT("格式化为指定小数位数的数字"),
        FORMAT_BYTES("将字节计数转换为带单位的值"),
        FORMAT_PICO_TIME("将以皮秒为单位的时间转换为带单位的值"),
        FOUND_ROWS("最近一次SELECT查询返回的行数"),
        FROM_BASE64("解码base64"),
        FROM_DAYS("将日数转换为日期"),
        FROM_UNIX_TIME("将 Unix 时间戳格式化为日期"),
        GEOMETRY_COLLECTION("从几何构造几何集合"),
        GET_DD_COLUMN_PRIVILEGES(""),
        GET_DD_CREATE_OPTIONS(""),
        GET_DD_INDEX_SUB_PART_LENGTH(""),
        GET_DATE_TIME_FORMAT("日期或时间格式字符串"), //GET_FORMAT(DATE,'USA') > %m.%d.%Y    GET_FORMAT(DATE,'ISO') > '%Y-%m-%d'  GET_FORMAT(TIME,'ISO') > '%H:%i:%s'
        GET_UTC_DATE("获取当前格林尼治标准时间"),
        GET_LOCK("获取命名锁"),
        GET_TZ("获取当前数据库的时区"),
        GREATEST("最大参数"),
        GROUP_CONCAT("串联分组字符串"),
        GROUP_REPLICATION_DISABLE_MEMBER_ACTION("禁用指定事件的成员作"),
        GROUP_REPLICATION_ENABLE_MEMBER_ACTION("为指定的事件启用成员作"),
        GROUP_REPLICATION_GET_COMMUNICATION_PROTOCOL("获取当前组复制通信协议的版本"),
        GROUP_REPLICATION_GET_WRITE_CONCURRENCY("获取当前为组设置的最大共识实例数"),
        GROUP_REPLICATION_RESET_MEMBER_ACTIONS("将所有成员作重置为默认值和配置版本 数字变为 1"),
        GROUP_REPLICATION_SET_AS_PRIMARY("将特定组成员设为主要组成员"),
        GROUP_REPLICATION_SET_COMMUNICATION_PROTOCOL("设置要使用的组复制通信协议的版本"),
        GROUP_REPLICATION_SET_WRITE_CONCURRENCY("设置可在 平行"),
        GROUP_REPLICATION_SWITCH_TO_MULTI_PRIMARY_MODE("将以单主模式运行的组的模式更改为 多主模式"),
        GROUP_REPLICATION_SWITCH_TO_SINGLE_PRIMARY_MODE("将以多主模式运行的组的模式更改为 单主模式"),
        GROUPING("区分超聚合 ROLLUP 行和常规行"),
        HEX("十进制或字符串值的十六进制表示"),
        HOUR("提取小时"),
        ICU_VERSION("ICU库版"),
        IF("IF"),
        IF_NULL("是否NULL"), //当输入的参数值为两个时，如果第一个参数值不为空，则返回第一个参数值，否则返回第二个参数值，若两者都为空，则返回空。当输入的参数为一个时，如果参数值为空，返回真，否则返回假
        IF_NULL_C("是否NULL"), //如果第一个字符串不为空，则返回第一个字符串，否则返回第二个字符串，若两者都为空，则返回空。
        IF_ELSE(""), //ORACLE中的DECODE DECODE(2, 1, 'a', 2, 'b', 'z');
        IN("值是否在一组值中"),
        INET_ATON("将标准的点分十进制IP地址转换为无符号整数"),
        INET_NTOA("将无符号整数转换为IPv4地址字符串"),
        INSERT("在指定位置插入子字符串"),
        INSTR("第一次出现的子字符串的索引"),
        INSERT_TEXT("用一个字符串替换另一个字符串中指定位置指定长度的子串"), //INSERT_TEXT('insert test', 8, 4, 'another') > insert another
        INSERT_TEXT_C("从指定的位置，删除指定的长度，再加入指定的字符串"), //INSERT_TEXT_C ('EXECUTE', 3, 1, 'AMPLE') > EXAMPLECUTE
        INTERNAL_AUTO_INCREMENT(""),
        INTERNAL_AVG_ROW_LENGTH(""),
        INTERNAL_CHECK_TIME(""),
        INTERNAL_CHECKSUM(""),
        INTERNAL_DATA_FREE(""),
        INTERNAL_DATA_LENGTH(""),
        INTERNAL_DD_CHAR_LENGTH(""),
        INTERNAL_GET_COMMENT_OR_ERROR(""),
        INTERNAL_GET_ENABLED_ROLE_JSON(""),
        INTERNAL_GET_HOSTNAME(""),
        INTERNAL_GET_USERNAME(""),
        INTERNAL_GET_VIEW_WARNING_OR_ERROR(""),
        INTERNAL_INDEX_COLUMN_CARDINALITY(""),
        INTERNAL_INDEX_LENGTH(""),
        INTERNAL_IS_ENABLED_ROLE(""),
        INTERNAL_IS_MANDATORY_ROLE(""),
        INTERNAL_KEYS_DISABLED(""),
        INTERNAL_MAX_DATA_LENGTH(""),
        INTERNAL_TABLE_ROWS(""),
        INTERNAL_UPDATE_TIME(""),
        INTERVAL("小于第一个参数的索引"),
        INTERVAL_YTM_COMPARE("比较两个 intervalytm 值"),
        INTERVAL_YTM_LARGER("比较两个 INTERVALYTM 值, 返回较大的值"),
        INTERVAL_YTM_SMALLER("比较两个 INTERVALYTM 值, 返回较小的值"),
        INTERVAL_DTS_COMPARE("比较两个 INTERVALDTS 值"),
        INTERVAL_DTS_LARGER("比较两个 INTERVALDTS 值, 返回较大的值"),
        INTERVAL_DTS_SMALLER("比较两个 INTERVALDTS 值, 返回较小的值"),
        IS("针对布尔值测试值"),
        IS_FINITE("否是有穷的日期时间"),
        IS_FREE_LOCK("命名锁是否空闲"),
        IS_NOT(""),
        IS_NOT_NULL(""),
        IS_NULL(""),
        IS_USED_LOCK("命名锁是否正在使用中"),
        IS_UUID("否为有效 UUID"),
        IS_FALSE("判断一个 bool 值是否为 FALSE"),
        IS_NOT_FALSE("判断一个 bool 值是否不为 FALSE"),
        IS_TRUE("判断一个 bool 值是否为 TRUE"),
        IS_NOT_TRUE("判断一个 bool 值是否不为 TRUE"),
        JSON_ARRAY("创建 JSON 数组"),
        JSON_ARRAY_APPEND("将数据附加到 JSON"),
        JSON_ARRAY_INSERT("插入 JSON 数组"),
        JSON_ARRAY_AGG("将结果集作为单个 JSON 数组"),
        JSON_CONTAINS("JSON在PATH上是否包含特定对象"),
        JSON_CONTAINS_PATH("JSON是否在PATH上包含任何数据"),
        JSON_DEPTH("JSON的最大深度"),
        JSON_EXTRACT("从JSON提取数据"),
        JSON_INSERT("将数据插入JSON"),
        JSON_KEYS("JSON中的键数组"),
        JSON_LENGTH("JSON中的元素数"),
        JSON_MERGE("合并 JSON，保留重复的键"),
        JSON_MERGE_PATCH("合并 JSON，替换重复键的值"),
        JSON_MERGE_PRESERVE("合并 JSON，保留重复的键"),
        JSON_OBJECT("创建 JSON 对象"),
        JSON_OBJECT_AGG("将结果集作为单个JSON对象"),
        JSON_OVERLAPS("比较两个 JSON，如果它们有任何 键值对或数组元素"),
        JSON_PRETTY("以可读的格式打印JSON"),
        JSON_QUOTE("将字符串转换为JSON格式"),
        JSON_REMOVE("从JSON中删除数据"),
        JSON_REPLACE("替换JSON中的值"),
        JSON_SCHEMA_VALID("根据JSON模式验证JSON"),
        JSON_SCHEMA_VALIDATION_REPORT("根据JSON模式验证JSON"),
        JSON_SEARCH("在JSON文档中搜索指定字符串"),
        JSON_SET("将数据插入JSON"),
        JSON_STORAGE_FREE("JSON 列值的二进制表示形式内释放的空间"),
        JSON_STORAGE_SIZE("用于存储JSON的二进制表示的空间"),
        JSON_TABLE("将JSON表达式中的数据作为关系表"),
        JSON_TYPE("JSON值的类型"),
        JSON_UNQUOTE("取消引用JSON值"),
        JSON_VALID("JSON值是否有效"),
        JSON_VALUE("从路径指向的位置的JSON中提取值"),
        JULIAN("计算给定日期的儒略日"),
        LAG("获取当前行前N行的值"),
        LAST_DAY("参数的当月最后一天"),
        LAST_INSERT_ID("最后一个 INSERT 的 AUTOINCREMENT 列的值"),
        LAST_VALUE("最后一行的参数值"),
        LOWER("小写"),
        LOWER_LIMIT("取字符串与其最近的下限"), //LOWER_LIMIT('ABC') > ABB
        LEAD("分区中当前行前导行的参数值"),
        LEAST("最小参数"),
        LEFT("指定的最左边的字符数"),
        LENGTH("字符串以字节为单位的长度"),
        LIKE("LIKE匹配"),
        POINT_TO_LINE_STRING("从点值构造 LineString"),
        LN("参数的自然对数"),
        LOAD_FILE("加载命名文件"),
        LOCAL_TIME(""),
        LOCAL_TIMESTAMP(""),
        LOCATE("第一次出现的子字符串的位置"),
        LOG("自然对数"),
        LOG10("以 10 为底的对数"),
        LOG2("以 2 为底的对数"),
        LPAD("字符串参数，左填充指定字符串"),
        LTRIM("删除前导空格"),
        MAKE_SET("根据二进制位选择对应的字符串参数，返回由指定位的字符串组成的集合"),
        PARSE_FROM_DATE("从年份和年份中的日期创建日期"), //MAKEDATE
        PARSE_FROM_TIME("从小时、分钟、秒创建时间"), //MAKETIME
        MASTER_POS_WAIT("阻粘直到副本读取并应用了所有更新"),
        MATCH("全文搜索"),
        MAX("最大值"),
        MBR_CONTAINS("判断一个几何对象的最小包围矩形（MBR）是否完全包含另一个几何对象的MBR"),
        MBR_COVERED_BY("一个 MBR 是否被另一个 MBR 覆盖"),
        MBR_COVERS("一个 MBR 是否涵盖另一个"),
        MBR_DISJOINT("两个几何形状的MBR是否不相交"),
        MBR_EQUALS("两个几何形状的MBR是否相等"),
        MBR_INTERSECTS("两个几何形状的 MBR 是否相交"),
        MBR_OVERLAPS("两个几何形状的 MBR 是否重叠"),
        MBR_TOUCHES("两个几何形状的 MBR 是否接触"),
        MBR_WITHIN("一个几何的 MBR 是否在另一个几何的 MBR 内"),
        MD5("MD5"),
        MEDIAN("中位数"),
        MEMBER_OF("检查一个值是否存在于数组中"),
        MICROSECOND("微秒"),
        MID("从指定位置开始的子字符串"),
        MIDNIGHT_SECONDS("计算指定的时间与午夜之间的秒数"),
        MIN("最小值"),
        MINUTE("分钟"),
        MOD("余数"),
        MONTH("月份"),
        MONTH_NAME("月份名称"),
        NEXT_VAL("序列值"),
        NEXT_DAY("指定日期 date 和星期 X, 求出星期 X 的日期"),
        NLS_SORT("将字符串转换为指定排序方式对应的二进制编码"),
        LINE_STRING_TO_MULTI_LINE_STRING("根据 LineString 值构建 MultiLineString"),
        POINT_TO_MULTI_POINT("根据 Point 值构造 MultiPoint"),
        POLYGON_TO_MULTI_POLYGON("从多边形值构造多边形集合"),
        NAME_CONST("指定列名"),
        NEW_ID("全球唯一标识符"),
        NOW("当前日期和时间"),
        NTH_VALUE("第 N 行的参数值"),
        NTILE("其分区中当前行的存储桶号"),
        NULLIF("如果expr1 = expr2 成立，那么返回值为NULL"),
        NUMBER_TO_YM_INTERVAL("将数值转换成 INTERVAL YEAR TO MONTH 类型"),
        NUMBER_TO_DS_INTERVAL("将数值转换成 INTERVAL DAY TO SECOND 类型"),
        OBJ_DESCRIPTION("获得对象的描述信息"),
        OCT("包含数字的八进制表示的字符串"),
        ORD("参数最左侧字符的字符代码"),
        OCTET_LENGTH("字节数"),
        OVERLAY("从指定的位置，取指定的长度，用另一个字符中来代替"),
        PAT_INDEX("一个字串在指定表达式中的起始位置，"),
        PERCENT_RANK("排名值百分比"),
        PERIOD_ADD("向年月添加期间"),
        PERIOD_DIFF("期间之间的月数"),
        PI("PI"),
        XY_TO_POINT("从坐标构造点"),
        LINE_STRING_TO_POLYGON("从 LineString 参数构造多边形"),
        POSITION("LOCATE"),
        POW("幂"),
        POWER("幂", POW),
        PWD_COMPARE("比较数据库用户显示密码和加密密码"),
        PS_CURRENT_THREAD_ID("当前线程的性能架构线程 ID"),
        PS_THREAD_ID("给定线程的性能架构线程 ID"),
        QUARTER("季度"),
        QUOTE("转义"),
        QUOTE_IDENT("输出字符串表达式"), //QUOTE_IDENT('a') > "a"
        QUOTE_LITERAL("输出字符串表达式"), //QUOTE_IDENT('a') > 'a'
        RADIANS("转换为弧度"),
        RAND("随机浮点值"),
        RANDOM("随机浮点值", RAND),
        RANDOM_INT("随机整数值"),
        RANDOM_BYTES("一个随机字节向量"),
        RANK("其分区中当前行的排名"),
        REBUILD_TABLE("重建所有表"),
        REGEXP("字符串是否与正则表达式匹配"),
        REGEXP_INSTR("子字符串匹配正则表达式的起始索引"),
        REGEXP_LIKE("字符串是否与正则表达式匹配"),
        REGEXP_REPLACE("替换与正则表达式匹配的子字符串"),
        REGEXP_SUBSTR("子字符串匹配正则表达式"),
        RELEASE_ALL_LOCKS("释放所有当前命名锁"),
        RELEASE_LOCK("释放命名锁"),
        REMOVE_TABLE_POLICY("取消应用策略到表"),
        REMOVE_TABLE_CONTROL("移除表级控制"),
        REMOVE_ROW_CONTROL("移除行级控制"),
        REMOVE_COLUMN_CONTROL("移除列级控制"),
        REMOVE_COLUMN_CONTROL_CONSTRAINT("移除列级控制推理约束"),
        REPEAT("重复字符串指定次数"),
        REPLACE("替换指定字符串的出现次数"),
        RESTATISTICS("重建所有统计信息"),
        REVERSE("反转字符串中的字符"),
        RIGHT("指定的最右边的字符数"),
        RLIKE("字符串是否与正则表达式匹配"),
        ROLES_GRAPHML("表示内存角色子图的 GraphML"),
        ROUND("四舍五入"),
        ROW_COUNT("更新的行数"),
        ROW_NUMBER("其分区中的当前行数"),
        RPAD("附加字符串指定次数"),
        RTRIM("删除尾随空格"),
        SCHEMA("SCHEMA"),
        SEC_TO_TIME("将秒转换为时间"),
        SECOND("秒"),
        SESSION_USER("当前用户"),
        SET_CONFIG("设置某个配置参数的值"),
        SET_TAB_CONTROL_BASE_TIME("设置基于时间段的列集合访问控制"),
        SET_VAL("设置一个序列的当前值"),
        SET_USER_PRIVILEGE("为用户授权特权"),
        SHA1("计算 SHA-1 160 位校验和"),
        SHA2("计算 SHA-2 校验和"),
        SIGN("符号"),
        SIN("正弦"),
        SHOW_BINLOG_EVENTS("获得指定 Binlog 文件的详细内容"),
        SLEEP("睡眠几秒钟"),
        SOUNDEX("SOUNDEX 值"),
        SOUNDS_LIKE("比较声音"),
        SOURCE_POS_WAIT("阻止直到副本读取并应用了所有更新"),
        SPACE("指定空格数的字符串"),
        SPLIT_PART("以给定的字符串为分隔符，来分隔另一个字符串，并取出指定的分隔部分"),
        SQRT("平方根"),
        ST_AREA("多边形或多多边形区域"),
        ST_TO_WKB("从内部几何格式转换为WKB"),
        ST_TO_GEO_JSON("从几何图形生成GEO JSON对象"),
        ST_TO_WKT("从内部几何格式转换为WKT"),
        ST_BUFFER("与几何给定距离内的点的几何"),
        ST_BUFFER_STRATEGY("生成ST_BUFFER的策略选项"),
        ST_CENTROID("质心作为点"),
        ST_COLLECT("将空间值聚合到集合中"),
        ST_CONTAINS("一个几何是否包含另一个几何"),
        ST_CONVEX_HULL("几何凸包"),
        ST_CROSSES("一个几何体是否与另一个几何体交叉"),
        ST_DIFFERENCE("两个几何形状的点设置差异"),
        ST_DIMENSION("几何尺寸"),
        ST_DISJOINT("一个几何是否与另一个几何不相交"),
        ST_DISTANCE("一个几何体与另一个几何体的距离"),
        ST_DISTANCE_SPHERE("两个几何形状之间的地球上最小距离"),
        ST_END_POINT("LINESTRING的终点"),
        ST_ENVELOPE("几何的MBR"),
        ST_EQUALS("一个几何是否等于另一个几何"),
        ST_EXTERIOR_RING("多边形的外环"),
        ST_FRECHET_DISTANCE("一个几何体与另一个几何体的离散FRÉCHET距离"),
        ST_GEOMETRY_HASH("生成地理哈希值"),
        ST_GEOMETRY_COLLECTION_FROM_TEXT("从WKT几何集合"),
        ST_GEOMETRY_COLLECTION_FROM_WKB("从WKB几何集合"),
        ST_GEOMETRY_N("从几何集合中第N个几何"),
        ST_GEOMETRY_TYPE("几何类型的名称"),
        ST_GEOMETRY_FROM_GEO_JSON("从GEOJSON对象生成几何图形"),
        ST_GEOMETRY_FROM_TEXT("从WKT几何"),
        ST_GEOMETRY_FROM_WKB("从WKB几何"),
        ST_HAUSDORFF_DISTANCE("一个几何与另一个几何的离散豪斯多夫距离"),
        ST_INTERIOR_RING_N("多边形的第N个内环"),
        ST_INTERSECTION("点集两个几何的交点"),
        ST_INTERSECTS("一个几何体是否与另一个几何体相交"),
        ST_IS_CLOSED("几何体是否封闭且简单"),
        ST_IS_EMPTY("几何是否为空"),
        ST_IS_SIMPLE("几何形状是否简单"),
        ST_IS_VALID("几何是否有效"),
        ST_LAT_FROM_GEO_HASH("从GEOHASH值纬度"),
        ST_LATITUDE("点的纬度"),
        ST_LENGTH("LINESTRING的长度"),
        ST_LINE_STRING_FROM_TEXT("从WKT构造LINESTRING"),
        ST_LINE_STRING_FROM_WKB("从WKB构造LINESTRING"),
        ST_LINE_INTERPOLATE_POINT("沿LINESTRING指向给定百分比"),
        ST_LINE_INTERPOLATE_POINTS("沿LINESTRING指向给定百分比的"),
        ST_LONG_FROM_GEO_HASH("从GEOHASH值经度"),
        ST_LONGITUDE("点的经度"),
        ST_MAKE_ENVELOPE("围绕两点的矩形"),
        ST_MULTI_LINE_STRING_FROM_TEXT("从WKT构造MULTILINESTRING"),
        ST_MULTI_LINE_STRING_FROM_WKB("从WKB构造MULTILINESTRING"),
        ST_MULTI_POINT_FROM_TEXT("从WKT构造MULTIPOINT"),
        ST_MULTI_POINT_FROM_WKB("从WKB构造MULTIPOINT"),
        ST_MULTI_POLYGON_FROM_TEXT("从WKT构造多多边形"),
        ST_MULTI_POLYGON_FROM_WKB("从WKB构造多多边形"),
        ST_NUM_GEOMETRIES("几何集合中的几何数"),
        ST_NUM_INTERIOR_RINGS("多边形中的内环数"),
        ST_NUM_POINTS("LINESTRING中的点数"),
        ST_OVERLAPS("一个几何体是否与另一个几何体重叠"),
        ST_POINT_AT_DISTANCE("沿LINESTRING给定距离的点"),
        ST_POINT_FROM_GEO_HASH("将地理哈希值转换为POINT值"),
        ST_POINT_FROM_TEXT("从WKT构造点"),
        ST_POINT_FROM_WKB("从WKB构造点"),
        ST_POINT_N("从LINESTRING第N个点"),
        ST_POLYGON_FROM_TEXT("从WKT构造多边形"),
        ST_POLYGON_FROM_WKB("从WKB构造多边形"),
        ST_SIMPLIFY("简化的几何"),
        ST_SRID("几何的空间参考系统ID"),
        ST_START_POINT("LINESTRING的起点"),
        ST_SWAP_XY("交换X/Y坐标的参数"),
        ST_SYM_DIFFERENCE("点集两个几何的对称差值"),
        ST_TOUCHES("一个几何体是否接触另一个几何体"),
        ST_TRANSFORM("变换几何坐标"),
        ST_UNION("点集两个几何的并集"),
        ST_VALIDATE("已验证的几何图形"),
        ST_WITHIN("一个几何是否在另一个几何中"),
        ST_X("点的X坐标"),
        ST_Y("点的Y坐标"),
        STRING_POSITION("确定二个 TEXT 串在第一个 TEXT 串中第一次出现的位置"),
        STATEMENT_DIGEST("计算语句摘要哈希值"),
        STATEMENT_DIGEST_TEXT("计算规范化语句摘要"),
        STD("总体标准差"),
        STDDEV("总体标准差"),
        STDDEV_POP("总体标准差"),
        STDDEV_SAMP("样本标准差"),
        STR_TO_DATE("将字符串转换为日期"),
        STRCMP("比较两个字符串"),
        SUBSTR("从指定的位置开始，截取定长子串"),
        SUBSTR_BIT("从指定的位置开始，按字节截取子串"),
        SUBSTRING("SUBSTRING"), //SUBSTRING('SUBSTRING',2 , 4) > UBST
        SUBSTRING_INDEX("从指定数量之前的字符串  子字符串分隔符的出现次数"),
        SUB_TIME("TIME1减去TIME2后的时间"),
        SUM("合计"),
        SYS_DATE("函数执行的时间"),
        SYSTEM_USER(""),
        SYS_CONTEXT("该函数用于获取上下文里属性的值"),
        SYS_GET_BLOCK_SIZE("存储块大小"),
        SYS_GET_EXTRA_NAME_CHARACTERS("得到所有用于 unquoted SQL 标识符的特别字符，除了 a-z,A-Z,0-9,_"),
        SYS_GET_HOME_DIR("获取数据库路径"),
        SYS_GET_PAGE_SIZE("存储页大小"),
        SYS_GET_PHY_DBNAME("获取数据库名"),
        SYS_GET_REL_ID("从模式名和表名得到表的 oid"),
        SYS_GET_SPC_HIT_RATE("计算 SPC 的命中率"),
        SYS_GET_SQL_KEYWORDS("取得所有关键字，用逗号隔开"),
        SYS_GET_USER_LOGIN_FAIL_COUNT("检查用户登路失败次数"),
        SYS_GUID("全球唯一标识符"),
        SYS_IS_CURRENT_USER_DBA("检查用户是不是 DBA"),
        SYS_KILL_SESSION("kill一个会话"),
        SYS_RESET_ALL_SESSION_STAT("重置所有 session 统计信息"),
        SYS_RESET_SESSION_STAT("重置指定 session 统计信息"),
        SYS_RESET_SPC_STAT("重置计算 SPC 的命中率"),
        TAN("切线"),
        TEXT_LARGER("比较字符串，取相应位在字符表中靠后的"),
        TEXT_SMALLER("比较字符串，取相应位在字符表中靠前的"),
        TIME("时间部分"),
        TIME_FORMAT("时间格式化"),
        TIME_OF_DAY(""),
        TIME_OVERLAPS("前后两个时间区域是否有重叠"), //OVERLAPS('12:12:12', '12:12:15', '12:12:16', '12:12:17')
        TIME_TO_SEC("转换为秒的参数"),
        TIME_DIFF("时间差"),
        TIME_SMALLER("最小时间"),
        TIME_LARGER("最大时间"),
        TIMESTAMP("时间戳"),
        TIMESTAMP_ADD("添加时间"),
        TIMESTAMP_COMPARE("比较两个 TIMESTAMP 值"),
        TIMESTAMP_DIFF("时间差"),
        TIMESTAMP_SMALLER("最小时间"),
        TIMESTAMP_LARGER("最大时间"),
        TO_BASE64("BASE64"),
        TO_CHAR("CHAR"),
        TO_DATE("将一个文本类型的 TIMESTAMP 类型数据，转换成 DATE 类型"),
        TO_DAYS("转换为天数"),
        TO_HEX("16进制"),
        TO_DECIMAL("转换成 NUMERIC 类型"),
        TO_NUMBER("转换成 NUMERIC 类型", TO_DECIMAL),
        TO_SECONDS("转换为秒"),
        TO_TIMESTAMP(""),
        TO_TIMESTAMP_TZ(""),
        TRANSLATE("将字符串中的指定子串转换成新的子串并返回"),
        TRIM("删除前导和尾随空格"),
        TRUNC("截断到指定的小数位数"),
        TRUNCATE("截断到指定的小数位数", TRUNC),
        UPPER("大写"),
        UPPER_LIMIT("取字符串与其最近的上限"),
        UMINUS("取反"),
        UN_COMPRESS("解压缩压缩的字符串"),
        UNCOMPRESSED_LENGTH("压缩前字符串的长度"),
        UN_HEX("包含数字十六进制表示的字符串"),
        UNIX_TIMESTAMP("UNIX 时间戳"),
        UPDATE_XML("替换XML片段"),
        USER("客户端提供的用户名和主机名"),
        UTC_DATE("当前 UTC 日期"),
        UTC_TIME("当前 UTC 时间"),
        UTC_TIMESTAMP("当前 UTC 时间戳"),
        UUID("UUID"),
        UUID_SHORT("整数值通用标识符"),
        UUID_TO_BIN("将字符串 UUID 转换为二进制"),
        VALIDATE_PASSWORD_STRENGTH("确定密码的强度"),
        VAR_POP("总体标准方差"),
        VAR_SAMP("样本方差"),
        VARIANCE("总体标准方差"),
        VERSION("服务器版本"),
        WAIT_FOR_EXECUTED_GTID_SET("等待给定的 GTID 在副本上执行"),
        WEEK("周数"),
        WEEKDAY("工作日索引"),
        WEEK_OF_YEAR("日期的日历周"),
        WEIGHT_STRING("字符串的权重字符串"),
        XOR("逻辑异或"),
        YEAR("年份"),
        YEAR_WEEK("年份和周"), //YEARWEEK(now())
        ;
        META(String title){
            this.title = title;
            this.synonym = null;
        }
        META(String title, META synonym) {
            this.title = title;
            this.synonym = synonym;
        }
        private final META synonym;
        private final String title;
        public String title() {
            return title;
        }
    }

    /**
     * 数据库类型
     * @return DatabaseType
     */
    DatabaseType database();

    /**
     * 参数,注意参数有可能是个函数
     * @return list
     */
    List<String> params();
    void params(List<String> params);

    /**
     * 转换后格式
     * @return 转换后格式
     */
    String formula();

    META meta();

}