<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.anyline</groupId>
        <artifactId>anyline-dependency</artifactId>
        <version>8.7.5-SNAPSHOT</version>
        <relativePath>../../anyline-dependency/pom.xml</relativePath>
    </parent>

    <artifactId>anyline-data-arango</artifactId>
    <packaging>jar</packaging>
    <name>anyline data arango</name>
    <url>http://www.anyline.org/arango</url>

    <dependencies>
        <dependency>
            <groupId>org.anyline</groupId>
            <artifactId>anyline-data</artifactId>
        </dependency>
        <dependency>
            <groupId>com.arangodb</groupId>
            <artifactId>arangodb-java-driver</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.json</groupId>
            <artifactId>jakarta.json-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.json</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>