/*
 * Copyright 2006-2023 www.anyline.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.anyline.metadata.type;

import org.anyline.adapter.KeyAdapter.KEY_CASE;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public enum DatabaseType implements Serializable {
        NONE			      ("NONE"	                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, "",""),
        COMMON                ("COMMON"	                                , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, "",""),
        Access                ("Microsoft Access"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 980  , "Microsoft Access", "sun.jdbc.odbc.JdbcOdbcDriver", "jdbc:odbc:driver={Microsoft Access Driver (*.mdb)};DBQ={database}"),
        Accumulo              ("Apache Accumulo"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 910  , null, null                , null                          ),
        Acebase               ("Acebase"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 624  , null, null                , null                          ),
        ActianFastObjects     ("Actian FastObjects"                        , DatabaseGenus.None        , KEY_CASE.SRC   , 710  , null, null                , null                          ),
        ActianNoSQL           ("Actian NoSQL Database"                     , DatabaseGenus.None        , KEY_CASE.SRC   , 838  , null, null                , null                          ),
        ActianPSQL            ("Actian PSQL"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 668  , null, null                , null                          ),
        ActianVector          ("Actian Vector"                             , DatabaseGenus.None        , KEY_CASE.SRC   , 790  , null, null                , null                          ),
        ActorDB               ("ActorDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 602  , null, null                , null                          ),
        Adabas                ("Adabas"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 919  , null, null                , null                          ),
        Adaptive              ("SAP Adaptive Server"                       , DatabaseGenus.None        , KEY_CASE.SRC   , 974  , null, "com.sybase.jdbc.SybDriver", "jdbc:sybase:Tds:{host}:{port}/{database}"),
        Aerospike             ("Aerospike"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 940  , null, "com.aerospike.jdbc.AerospikeDriver", "jdbc:aerospike:{host}:{port}/{namespace}"),
        AgensGraph            ("AgensGraph"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 612  , null, null                , null                          ),
        AlaSQL                ("AlaSQL"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 765  , null, null                , null                          ),
        Algolia               ("Algolia"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 938  , null, null                , null                          ),
        AllegroGraph          ("AllegroGraph"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 807  , null, null                , null                          ),
        Altibase              ("Altibase"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 786  , null, null                , null                          ),
        AmazonAurora          ("Amazon Aurora"                             , DatabaseGenus.None        , KEY_CASE.SRC   , 950  , null, null                , null                          ),
        AmazonCloudSearch     ("Amazon CloudSearch"                        , DatabaseGenus.None        , KEY_CASE.SRC   , 867  , null, null                , null                          ),
        AmazonDocumentDB      ("Amazon DocumentDB"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 857  , null, null                , null                          ),
        AmazonDynamoDB        ("Amazon DynamoDB"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 983  , null, null                , null                          ),
        AmazonKeyspaces       ("Amazon Keyspaces"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 782  , null, null                , null                          ),
        AmazonNeptune         ("Amazon Neptune"                            , DatabaseGenus.None        , KEY_CASE.SRC   , 872  , null, null                , null                          ),
        AmazonRedshift        ("Amazon Redshift"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 966  , null, "com.amazon.redshift.jdbc4.Driver", "jdbc:redshift://{host}:{port}/{database}"),
        AmazonSimpleDB        ("Amazon SimpleDB"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 869  , null, null                , null                          ),
        AmazonTimestream      ("Amazon Timestream"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 785  , null, null                , null                          ),
        AnalyticDBMySQL       ("Alibaba Cloud AnalyticDB for MySQL"        , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 759  , null, "com.mysql.cj.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        AnalyticDBPostgreSQL  ("Alibaba Cloud AnalyticDB for PostgreSQL"   , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 734  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        AntDB                 ("AntDB"                                     , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 696  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        Anywhere              ("SAP Anywhere"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "com.sybase.jdbc4.jdbc.SybDriver", "jdbc:sybase:Tds:{host}:{port}/{database}"),
        AnzoGraph_DB          ("AnzoGraph DB"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 707  , null, null                , null                          ),
        ApsaraDBPolarDB       ("Alibaba Cloud ApsaraDB for PolarDB"        , DatabaseGenus.None        , KEY_CASE.SRC   , 720  , null, "com.aliyun.polardb.Driver", "jdbc:polardb://{host}:{port:3306}/{database}"),
        ArangoDB              ("ArangoDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 916  , null, null                , null                          ),
        ArcadeDB              ("ArcadeDB"                                  , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 658  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        ArgoDB                ("Transwarp ArgoDB(星环)"                      , DatabaseGenus.None        , KEY_CASE.SRC   , 621  , null, null                , null                          ),
        atoti                 ("atoti"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 743  , null, null                , null                          ),
        Axibase               ("Axibase"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 718  , null, "com.axibase.tsd.driver.jdbc.AtsdDriver", "jdbc:atsd://{host}:{port}"   ),
        AzureCosmos           ("Microsoft Azure Cosmos DB"                 , DatabaseGenus.None        , KEY_CASE.SRC   , 972  , null, null                , null                          ),
        AzureDataExplorer     ("Microsoft Azure Data Explorer"             , DatabaseGenus.None        , KEY_CASE.SRC   , 939  , null, null                , null                          ),
        AzureSearch           ("Microsoft Azure Search"                    , DatabaseGenus.None        , KEY_CASE.SRC   , 933  , null, null                , null                          ),
        AzureSQL              ("Microsoft Azure SQL Database"              , DatabaseGenus.None        , KEY_CASE.SRC   , 984  , null, null                , null                          ),
        AzureSynapse          ("Microsoft Azure Synapse Analytics"         , DatabaseGenus.None        , KEY_CASE.SRC   , 969  , null, null                , null                          ),
        AzureTableStorage     ("Microsoft Azure Table Storage"             , DatabaseGenus.None        , KEY_CASE.SRC   , 931  , null, null                , null                          ),
        Badger                ("Badger"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 661  , null, null                , null                          ),
        BadgerDB              ("BadgerDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        Bangdb                ("Bangdb"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 674  , null, null                , null                          ),
        BaseX                 ("BaseX"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 860  , null, null                , null                          ),
        BergDB                ("BergDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 594  , null, null                , null                          ),
        BigchainDB            ("BigchainDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 794  , null, null                , null                          ),
        BigObject             ("BigObject"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 654  , null, null                , null                          ),
        Blazegraph            ("Blazegraph"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 783  , null, null                , null                          ),
        Blueflood             ("Blueflood"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 644  , null, null                , null                          ),
        BoltDB                ("BoltDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 744  , null, null                , null                          ),
        BrightstarDB          ("BrightstarDB"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 628  , null, null                , null                          ),
        Brytlyt               ("Brytlyt"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 712  , null, null                , null                          ),
        Cache                 ("InterSystems Cache"                        , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "com.intersys.jdbc.CacheDriver", "jdbc:Cache://{host}:{port}/{database}"),
        Cachelot              ("Cachelot"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 610  , null, null                , null                          ),
        Cassandra             ("Cassandra"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 987  , null, "org.apache.cassandra.cql.jdbc.CassandraDriver", "jdbc:cassandra://{host}:{port/{database}"),
        Cayley                ("Cayley"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        ChinaMobileDB         ("磐维数据库"                                     , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        ChinaUnicomDB         ("中国联通"                                      , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        Chroma                ("Chroma"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 859  , null, null                , null                          ),
        CirroData             ("东方国信"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "com.bonc.xcloud.jdbc.XCloudDriver", "jdbc:xcloud:@{host}:{port}/{database}"),
        Citus                 ("Citus"                                     , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 878  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        ClickHouse            ("ClickHouse"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 960  , null, "com.clickhouse.jdbc.ClickHouseDriver", "jdbc:clickhouse://{host}:{port:8123}/{database}"),
        Cloudant              ("IBM Cloudant"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 898  , null, null                , null                          ),
        Cloudera              ("Cloudera "                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 962  , null, "com.cloudera.impala.jdbc41.Driver", "jdbc:impala://{host}:{port}/{database}"),
        CloudKit              ("CloudKit"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 889  , null, null                , null                          ),
        CnosDB                ("CnosDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 729  , null, null                , null                          ),
        CockroachDB           ("CockroachDB"                               , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 935  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        Comdb2                ("Comdb2"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 683  , null, "com.bloomberg.comdb2.jdbc.Driver", "jdbc:comdb2://{host}:{port}/{database}"),
        ComputeDB             ("Tibco ComputeDB"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 678  , null, null                , null                          ),
        CortexDB              ("CortexDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 593  , null, null                , null                          ),
        Couchbase             ("Couchbase"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 967  , null, null                , "couchbases://{database}"     ),
        CouchDB               ("CouchDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 953  , null, null                , null                          ),
        CovenantSQL           ("CovenantSQL"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 592  , null, null                , null                          ),
        Coveo                 ("Coveo"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 876  , null, null                , null                          ),
        Crase                 ("Crase"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        CrateDB               ("CrateDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 768  , null, null                , null                          ),
        CrispI                ("CrispI"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        CubicWeb              ("CubicWeb"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 667  , null, null                , null                          ),
        Cubrid                ("Cubrid"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 826  , null, null                , null                          ),
        D3                    ("D3"                                        , DatabaseGenus.None        , KEY_CASE.SRC   , 825  , null, null                , null                          ),
        DaggerDB              ("DaggerDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 591  , null, null                , null                          ),
        Databend              ("Databend"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 739  , null, null                , null                          ),
        Databricks            ("Databricks"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 982  , null, null                , "jdbc:databricks://{host}:{port};HttpPath={path}"),
        DatacomDB             ("Datacom/DB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 772  , null, null                , null                          ),
        DataEase              ("DataEase"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 827  , null, null                , null                          ),
        DataFS                ("DataFS"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 615  , null, null                , null                          ),
        Datameer              ("Datameer"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 840  , null, null                , null                          ),
        Datastax              ("Datastax Enterprise"                       , DatabaseGenus.None        , KEY_CASE.SRC   , 941  , null, null                , null                          ),
        Datomic               ("Datomic"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 864  , null, null                , null                          ),
        DB2                   ("IBM Db2"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 990  , null, "com.ibm.db2.jcc.DB2Driver", "jdbc:db2://{host}:{port:50000}/{database}"),
        Db2Warehouse          ("IBM Db2 warehouse"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 833  , null, "com.ibm.db2.jcc.DB2Driver", "jdbc:db2://{host}:{port:50000}/{database}"),
        Db4o                  ("Db4o"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 850  , null, null                , null                          ),
        dbase                 ("dBASE"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 957  , null, null                , null                          ),
        DBISAM                ("DBISAM"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 791  , null, null                , null                          ),
        DeepLake              ("Deep Lake"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 697  , null, null                , null                          ),
        Derby                 ("Derby"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 936  , null, "org.apache.derby.jdbc.EmbeddedDriver", "jdbc:derby:{database}"       ),
        Dgraph                ("Dgraph"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 846  , null, null                , null                          ),
        DM                    ("达梦"                                        , DatabaseGenus.Oracle      , KEY_CASE.SRC   , 990  , null, "dm.jdbc.driver.DmDriver", "jdbc:dm://{host}:{port:5236}/{database}"),
        DolphinDB             ("DolphinDB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 905  , null, "com.dolphindb.jdbc.Driver", "jdbc:dolphindb://{host}:{port}"),
        Dolt                  ("Dolt"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 788  , null, null                , null                          ),
        Doris                 ("Apache Doris"                              , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 756  , null, "com.mysql.cj.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Dragonfly             ("Dragonfly"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 651  , null, null                , null                          ),
        Drill                 ("Apache Drill"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 886  , null, null                , null                          ),
        DuckDB                ("DuckDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 906  , null, "org.duckdb.DuckDBDriver", "jdbc:duckdb:{database}"      ),
        Dydra                 ("Dydra"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 673  , null, null                , null                          ),
        EDB                   ("EDB"                                       , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 883  , null, "org.postgresql.Driver", "jdbc:edb://{host}:{port:5444}/{database}"),
        EdgelessDB            ("EdgelessDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 590  , null, null                , null                          ),
        Ehcache               ("Ehcache"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 937  , null, null                , null                          ),
        EJDB                  ("EJDB"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 699  , null, null                , null                          ),
        Elassandra            ("Elassandra"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 726  , null, null                , null                          ),
        ElasticSearch         ("Elasticsearch"                             , DatabaseGenus.None        , KEY_CASE.SRC   , 991  , null, null                , null                          ),
        ElevateDB             ("ElevateDB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 688  , null, null                , null                          ),
        Elliptics             ("Elliptics"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 727  , null, null                , null                          ),
        Eloquera              ("Eloquera"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 647  , null, null                , null                          ),
        Empress               ("Empress"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 858  , null, null                , null                          ),
        EsgynDB               ("EsgynDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 679  , null, "org.trafodion.jdbc.t4.T4Driver", "jdbc:t4jdbc://{host}:{port}/"),
        etcd                  ("etcd"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 947  , null, null                , null                          ),
        EventStore            ("IBM Db2 Event Store"                       , DatabaseGenus.None        , KEY_CASE.SRC   , 671  , null, "com.ibm.db2.jcc.DB2Driver", "jdbc:db2://{host}:{port:50000}/{database}"),
        EXASOL                ("EXASOL"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 887  , null, "com.exasol.jdbc.EXADriver", "jdbc:exa:{host}:{port}"      ),
        eXistdb               ("eXist-db"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 777  , null, null                , null                          ),
        Exorbyte              ("Exorbyte"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 666  , null, null                , null                          ),
        eXtreme               ("eXtremeDB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 767  , null, "com.mcobject.jdbc.McoDriver", "jdbc:extremedb:{host}:{port}"),
        eXtremeScale          ("WebSphere eXtreme Scale"                   , DatabaseGenus.None        , KEY_CASE.SRC   , 776  , null, null                , null                          ),
        Ezmeral               ("HPE Ezmeral Data Fabric"                   , DatabaseGenus.None        , KEY_CASE.SRC   , 808  , null, null                , null                          ),
        FaircomDB             ("Faircom DB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 685  , null, "ctree.jdbc.ctreeDriver", "jdbc:ctree://{host}:{port}/{database}"),
        FaircomEDGE           ("Faircom EDGE"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 611  , null, "ctree.jdbc.ctreeDriver", "jdbc:ctree://{host}:{port}/{database}"),
        Fauna                 ("Fauna"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 841  , null, null                , null                          ),
        FeatureBase           ("FeatureBase"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 715  , null, null                , null                          ),
        FileMaker             ("FileMaker"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 978  , null, "com.filemaker.jdbc.Driver", "jdbc:filemaker://{host}:{port};{database}"),
        Firebase              ("Firebase Realtime Database"                , DatabaseGenus.None        , KEY_CASE.SRC   , 961  , null, null                , null                          ),
        Firebird              ("Firebird"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 968  , null, "org.firebirdsql.jdbc.FBDriver", "jdbc:firebirdsql://{host}:{port:3050}/{database}"),
        Firebolt              ("Firebolt"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 865  , null, null                , "jdbc:firebolt:{database}"    ),
        Flink                 ("Apache Flink"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 954  , null, null                , null                          ),
        FlockDB               ("FlockDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 692  , null, null                , null                          ),
        Fluree                ("Fluree"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 706  , null, null                , null                          ),
        FoundationDB          ("FoundationDB"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 835  , null, null                , null                          ),
        FrontBase             ("FrontBase"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 753  , null, "com.frontbase.jdbc.FBJDriver", "jdbc:FrontBase://{host}:{port}{database}"),
        Fujitsu               ("Fujitsu Enterprise Postgres"               , DatabaseGenus.None        , KEY_CASE.SRC   , 693  , null, null                , null                          ),
        FusionInsight         ("FusionInsight"                             , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "org.apache.hive.jdbc.HiveDriver", "jdbc:hive2://{host}:{port}/{database}"),
        GaiaDB                ("百度GaiaDB-X"                                , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 900  , null, "com.mysql.cj.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Galaxybase            ("Galaxybase"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 616  , null, null                , null                          ),
        GaussDB100            ("GaussDB 100"                               , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "com.huawei.gauss.jdbc.ZenithDriver", "jdbc:zenith:@{host}:{port}"  ),
        GaussDB200            ("GaussDB 200"                               , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "com.huawei.gauss200.jdbc.Driver", "jdbc:gaussdb://{host}:{port:25308}/{database}"),
        GBase8a               ("南大通用GBase8a"                               , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 990  , null, "com.gbase.jdbc.Driver", "jdbc:gbase://{host}:{port:5258}/{database}"),
        GBase8c               ("南大通用GBase8c"                               , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 990  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:15432}/{database}"),
        GBase8s               ("南大通用GBase8s"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 990  , null, "com.gbasedbt.jdbc.Driver", "jdbc:gbasedbt-sqli://{host}:{port:1533}/{database}:GBASEDBTSERVER={server};user={user};password={password}"),
        GemFire               ("GemFire"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 904  , null, null                , null                          ),
        GemStoneS             ("GemStone/S"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 758  , null, null                , null                          ),
        Geode                 ("Geode"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 870  , null, null                , null                          ),
        GeoMesa               ("GeoMesa"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 778  , null, null                , null                          ),
        GigaSpaces            ("GigaSpaces"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 813  , null, "com.j_spaces.jdbc.driver.GDriver", "jdbc:gigaspaces:url:jini://{host}"),
        Giraph                ("Giraph"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 822  , null, null                , null                          ),
        GoldenDB              ("GoldenDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "com.goldendb.jdbc.Driver", "jdbc:goldendb://{host}:{port}/{database}"),
        GoogleBigQuery        ("Google BigQuery"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 980  , null, null                , null                          ),
        GoogleBigtable        ("Google Cloud Bigtable"                     , DatabaseGenus.None        , KEY_CASE.SRC   , 912  , null, null                , null                          ),
        GoogleDatastore       ("Google Cloud Datastore"                    , DatabaseGenus.None        , KEY_CASE.SRC   , 922  , null, null                , null                          ),
        GoogleFirestore       ("Google Cloud Firestore"                    , DatabaseGenus.None        , KEY_CASE.SRC   , 952  , null, null                , null                          ),
        GoogleSpanner         ("Google Cloud Spanner"                      , DatabaseGenus.None        , KEY_CASE.SRC   , 902  , null, null                , null                          ),
        GraphBase             ("GraphBase"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 665  , null, null                , null                          ),
        GraphDB               ("GraphDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 879  , null, null                , null                          ),
        GraphEngine           ("Graph Engine"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 745  , null, null                , null                          ),
        Graphite              ("Graphite"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 921  , null, null                , null                          ),
        GraphPortal           ("Graph Portal"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        GreatDB               ("万里数据库"                                     , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 900  , null, "com.mysql.cj.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Greenplum             ("Greenplum"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 951  , null, "com.pivotal.jdbc.GreenplumDriver", "jdbc:pivotal:greenplum://{host}:{port};DatabaseName={database}"),
        GreptimeDB            ("GreptimeDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 660  , null, null                , null                          ),
        GridDB                ("GridDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 852  , null, "com.toshiba.mwcloud.gs.sql.Driver", "jdbc:gs://{host}:{port}/{cluster}/{database}"),
        GridGain              ("GridGain"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 847  , null, "org.apache.ignite.IgniteJdbcThinDriver", "jdbc:ignite:thin://{host}:{port}"),
        Grinn                 ("Grinn"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        gStore                ("gStore"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 631  , null, null                , null                          ),
        GTM                   ("GT.M"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 821  , null, null                , null                          ),
        H2                    ("H2"                                        , DatabaseGenus.None        , KEY_CASE.SRC   , 949  , null, "org.h2.Driver"     , "jdbc:h2:{database}"          ),
        H2GIS                 ("H2GIS"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 649  , null, null                , null                          ),
        HANA                  ("SAP HANA"                                  , DatabaseGenus.Oracle      , KEY_CASE.SRC   , 976  , null, "com.sap.db.jdbc.Driver", "jdbc:sap://{host}:{port}[?{param}]"),
        HarperDB              ("HarperDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 736  , null, "cdata.jdbc.harperdb.HarperDBDriver", "jdbc:harperdb:Server={host};User={user};Password={password};"),
        HashData              ("酷克数据"                                      , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        Hawkular              ("Hawkular Metrics"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 613  , null, null                , null                          ),
        HAWQ                  ("Apache HAWQ"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 805  , null, null                , null                          ),
        Hazelcast             ("Hazelcast"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 944  , null, null                , null                          ),
        Hbase                 ("HBase"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 973  , null, "org.apache.phoenix.jdbc.PhoenixDriver", "jdbc:phoenix:{host}:{port}/{database}"),
        HEAVYAI               ("HEAVY.AI"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 893  , null, "ai.heavy.jdbc.HeavyAIDriver", "jdbc:heavyai:{host}:{port}:{database}"),
        Helium                ("Helium"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 589  , null, null                , null                          ),
        Heroic                ("Heroic"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 750  , null, null                , null                          ),
        HFSQL                 ("HFSQL"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 819  , null, null                , null                          ),
        HGraphDB              ("HGraphDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 588  , null, null                , null                          ),
        Hibari                ("Hibari"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 789  , null, null                , null                          ),
        HighGo                ("瀚高"                                        , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 980  , null, "com.highgo.jdbc.Driver", "jdbc:highgo://{host}:{port:5866}/{database}"),
        Hippo                 ("Transwarp Hippo"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 625  , null, null                , null                          ),
        Hive                  ("Hive"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 981  , null, "org.apache.hive.jdbc.HiveDriver", "jdbc:hive2://{host}:{port}/{database}"),
        HotDB                 ("热璞"                                        , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 900  , null, "com.mysql.cj.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        HugeGraph             ("HugeGraph"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 677  , null, null                , null                          ),
        HyperGraphDB          ("HyperGraphDB"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 701  , null, null                , null                          ),
        HyperLevelDB          ("HyperLevelDB"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 646  , null, null                , null                          ),
        HyperSQL              ("HyperSQL(HSQLDB)"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 920  , null, "org.hsqldb.jdbcDriver", "jdbc:hsqldb:file:{database}" ),
        iBoxDB                ("iBoxDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 609  , null, null                , null                          ),
        IDMS                  ("IDMS"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 780  , null, null                , null                          ),
        Ignite                ("Ignite"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 913  , null, "org.apache.ignite.IgniteJdbcThinDriver", null                          ),
        Immudb                ("Immudb"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 705  , null, null                , null                          ),
        IMS                   ("IMS"                                       , DatabaseGenus.None        , KEY_CASE.SRC   , 875  , null, null                , null                          ),
        Indica                ("Indica"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 629  , null, null                , null                          ),
        Infinispan            ("Infinispan"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, null                , null                          ),
        InfiniteGraph         ("InfiniteGraph"                             , DatabaseGenus.None        , KEY_CASE.SRC   , 722  , null, null                , null                          ),
        InfinityDB            ("InfinityDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 627  , null, null                , null                          ),
        InfluxDB              ("InfluxDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 971  , null, null                , "jdbc:influxdb://{host}:{port}/{database}"),
        Infobright            ("Infobright"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 834  , null, null                , null                          ),
        Informix              ("Informix"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 965  , null, "com.informix.jdbc.IfxDriver", "jdbc:informix-sqli://{host}:{port}/{database}:INFORMIXSERVER={server}"),
        Ingres                ("Ingres"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 926  , null, null                , null                          ),
        Intelligence          ("Edge Intelligence"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 601  , null, null                , null                          ),
        Interbase             ("Interbase"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 932  , null, "interbase.interclient.Driver", "jdbc:interbase://{host}/{database}"),
        IoTDB                 ("Apache IoTDB"                              , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 798  , null, "org.apache.iotdb.jdbc.IoTDBDriver", null                          ),
        IRIS                  ("InterSystems IRIS"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 881  , null, "com.intersystems.jdbc.IRISDriver", "jdbc:IRIS://{host}:{port}/{database}"),
        ITTIA                 ("ITTIA"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 728  , null, null                , null                          ),
        Jackrabbit            ("Jackrabbit"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 929  , null, null                , null                          ),
        Jade                  ("Jade"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 731  , null, null                , null                          ),
        JaguarDB              ("JaguarDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 619  , null, "com.jaguar.jdbc.JaguarDriver", "new JaguarDataSource( {host},{port},{database})"),
        JanusGraph            ("JanusGraph"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 856  , null, null                , null                          ),
        JasDB                 ("JasDB"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 587  , null, null                , null                          ),
        jBASE                 ("jBASE"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 861  , null, null                , null                          ),
        Jena                  ("Apache Jena - TDB"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 915  , null, null                , null                          ),
        JethroData            ("JethroData"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 595  , null, null                , null                          ),
        KairosDB              ("KairosDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 764  , null, null                , null                          ),
        Kdb                   ("Kdb"                                       , DatabaseGenus.None        , KEY_CASE.SRC   , 948  , null, null                , null                          ),
        KeyDB                 ("KeyDB"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 761  , null, null                , null                          ),
        Kinetica              ("Kinetica"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 763  , null, null                , null                          ),
        KingBase              ("人大金仓"                                      , DatabaseGenus.Postgres    , KEY_CASE.UPPER , 900  , null, "com.kingbase8.Driver", "jdbc:kingbase8://{host}:{port:54321}/{database}"),
        KunDB                 ("星环"                                        , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 657  , null, "com.mysql.cj.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Kyligence             ("Kyligence Enterprise"                      , DatabaseGenus.None        , KEY_CASE.SRC   , 716  , null, "org.apache.kylin.jdbc.Driver", "jdbc:kylin://{host}:{port}/{project}"),
        kylin                 ("Apache Kylin"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 823  , null, "org.apache.kylin.jdbc.Driver", "jdbc:kylin://{host}:{port:7070}/{database}"),
        LeanXcale             ("LeanXcale"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 695  , null, "com.leanxcale.client.Driver", "jdbc:leanxcale://{host}:{port:1522}/{database}"),
        LedisDB               ("LedisDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 605  , null, null                , null                          ),
        LevelDB               ("LevelDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 895  , null, null                , null                          ),
        LightDB               ("恒生电子"                                      , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        Linter                ("Linter"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 653  , null, null                , null                          ),
        LiteDB                ("LiteDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 829  , null, null                , null                          ),
        LMDB                  ("LMDB"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 874  , null, null                , null                          ),
        LokiJS                ("LokiJS"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 741  , null, null                , null                          ),
        Lovefield             ("Lovefield"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 714  , null, null                , null                          ),
        M3DB                  ("M3DB"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 806  , null, null                , null                          ),
        MachbaseNeo           ("Machbase Neo"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 711  , null, "com.machbase.jdbc.MachDriver", "jdbc:machbase://{host}:{port:5656}/{database}"),
        ManticoreSearch       ("Manticore Search"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 652  , null, null                , null                          ),
        MapDB                 ("MapDB"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 770  , null, null                , null                          ),
        MariaDB               ("MariaDB"                                   , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 986  , null, "org.mariadb.jdbc.Driver", "jdbc:mysql://{host}:{port}/{database}"),
        MarkLogic             ("MarkLogic"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 945  , null, null                , null                          ),
        Marqo                 ("Marqo"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 700  , null, null                , null                          ),
        MatrixOne             ("MatrixOne"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 817  , null, null                , null                          ),
        MaxCompute            ("Alibaba Cloud MaxCompute"                  , DatabaseGenus.None        , KEY_CASE.SRC   , 762  , null, "com.aliyun.odps.jdbc.OdpsDriver", "jdbc:odps:{host}?project={database}"),
        MaxDB                 ("MaxDB"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 899  , null, "com.sap.dbtech.jdbc.DriverSapDB", "jdbc:sapdb://{host}:{port}/{database}"),
        Meilisearch           ("Meilisearch"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 818  , null, null                , null                          ),
        Memcached             ("Memcached"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 964  , null, null                , null                          ),
        Memgraph              ("Memgraph"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 892  , null, null                , null                          ),
        Milvus                ("Milvus"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 828  , null, null                , null                          ),
        Mimer_SQL             ("Mimer SQL"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 704  , null, null                , null                          ),
        Mnesia                ("Mnesia"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 855  , null, null                , null                          ),
        Model204              ("Model 204"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 796  , null, null                , null                          ),
        ModeShape             ("ModeShape"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 733  , null, null                , null                          ),
        MogDB                 ("MogDB"                                     , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "org.opengauss.Driver", "jdbc:opengauss://{host}:{port:5432}/{database}"),
        MonetDB               ("MonetDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 862  , null, "org.monetdb.jdbc.MonetDriver", "jdbc:monetdb://{host}:{port}/{database}"),
        MongoDB               ("MongoDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 993  , "mongodb:", null                , "mongodb://[{user}:{password}@]{host}:{port:27017}/{database}"),
        mSQL                  ("mSQL"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 830  , null, null                , null                          ),
        MSSQL                 ("SQL Server 2005+"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 996  , "", "com.microsoft.sqlserver.jdbc.SQLServerDriver", "jdbc:sqlserver://{host}:{port:1433};databaseName={database}"),
        MSSQL2000             ("SQL Server 2000"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 980  , ":microsoft:sqlserver:", "com.microsoft.jdbc.sqlserver.SQLServerDriver", "jdbc:microsoft:sqlserver://{host}:{port:1433};databaseName={database}"),
        MuDB                  ("MuDB"                                      , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        Mulgara               ("Mulgara"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 694  , null, null                , null                          ),
        MyScale               ("MyScale"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 655  , null, null                , null                          ),
        MYSQL                 ("MySQL"                                     , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 999  , null, "com.mysql.cj.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        NCache                ("NCache"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 801  , null, null                , null                          ),
        Nebula                ("Nebula"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 873  , null, "NebulaDriver"      , "jdbc:nebula://{host}"        ),
        Neo4j                 ("Neo4j"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 980  , null, "org.neo4j.jdbc.Driver", "jdbc:neo4j:http://{host}:{port:7474}"),
        Netezza               ("Netezza"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 956  , null, "org.netezza.Driver", "jdbc:netezza://{host}:{port}/{database}"),
        NEventStore           ("NEventStore"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 684  , null, null                , null                          ),
        Newts                 ("Newts"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 603  , null, null                , null                          ),
        NexusDB               ("NexusDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 747  , null, null                , null                          ),
        NonStopSQL            ("NonStop SQL"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 832  , null, null                , null                          ),
        NosDB                 ("NosDB"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 626  , null, null                , null                          ),
        NSDb                  ("NSDb"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 620  , null, null                , null                          ),
        NuoDB                 ("NuoDB"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 802  , null, "com.nuodb.jdbc.Driver", "jdbc:com.nuodb://{host}:{port}/{database}"),
        ObjectBox             ("ObjectBox"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 820  , null, null                , null                          ),
        ObjectDB              ("ObjectDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 784  , null, null                , null                          ),
        ObjectivityDB         ("Objectivity/DB"                            , DatabaseGenus.None        , KEY_CASE.SRC   , 769  , null, null                , null                          ),
        ObjectStore           ("ObjectStore"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 831  , null, null                , null                          ),
        OceanBase             ("OceanBase"                                 , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 842  , null, "com.oceanbase.jdbc.Driver", "jdbc:oceanbase://{host}:{port}/{database}"),
        ODABA                 ("ODABA"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        OpenEdge              ("OpenEdge"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 907  , null, "com.ddtek.jdbc.openedge.OpenEdgeDriver", "jdbc:datadirect:openedge://{host}:{port};databaseName={database};user={user};password={password}"),
        OpenGauss             ("openGauss"                                 , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 800  , null, "org.opengauss.Driver", "jdbc:opengauss://{host}:{port:5432}/{database}"),
        openGemini            ("openGemini"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 634  , null, null                , null                          ),
        OpenInsight           ("OpenInsight"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 760  , null, null                , null                          ),
        OpenQM                ("OpenQM"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 709  , null, null                , null                          ),
        OpenSearch            ("OpenSearch"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 955  , null, null                , null                          ),
        OpenTSDB              ("OpenTSDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 844  , null, null                , null                          ),
        ORACLE                ("Oracle"                                    , DatabaseGenus.Oracle      , KEY_CASE.SRC   , 997  , null, "oracle.jdbc.OracleDriver", "jdbc:oracle:thin:@{host}:{port:1521}/{database}"),
        OracleBerkeley        ("Oracle Berkeley DB"                        , DatabaseGenus.None        , KEY_CASE.SRC   , 897  , null, null                , null                          ),
        OracleCoherence       ("Oracle Coherence"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 871  , null, null                , null                          ),
        OracleEssbase         ("Oracle Essbase"                            , DatabaseGenus.None        , KEY_CASE.SRC   , 942  , null, null                , null                          ),
        OracleNoSQL           ("Oracle NoSQL"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 908  , null, null                , null                          ),
        OracleRdb             ("Oracle Rdb"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 814  , null, null                , null                          ),
        OrientDB              ("OrientDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 903  , null, null                , null                          ),
        OrigoDB               ("OrigoDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 640  , null, null                , null                          ),
        oscar                 ("神舟通用"                                      , DatabaseGenus.Oracle      , KEY_CASE.SRC   , 990  , null, "com.oscar.Driver"  , "jdbc:oscar://{host}:{port:2003}/{database}"),
        OushuDB               ("OushuDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 630  , null, null                , null                          ),
        OWASP                 ("OWASP"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        PerconaMongoDB        ("Percona Server for MongoDB"                , DatabaseGenus.None        , KEY_CASE.SRC   , 746  , null, null                , null                          ),
        PerconaMySQL          ("Percona Server for MySQL"                  , DatabaseGenus.None        , KEY_CASE.SRC   , 868  , null, null                , null                          ),
        Perst                 ("Perst"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 816  , null, null                , null                          ),
        Phoenix               ("Apache Phoenix"                            , DatabaseGenus.None        , KEY_CASE.SRC   , 884  , null, "org.apache.phoenix.jdbc.PhoenixDriver", "jdbc:phoenix:{host}:{port:2181}/{database}"),
        PieCloudDB            ("PieCloudDB"                                , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 690  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        Pinecone              ("Pinecone"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 894  , null, null                , null                          ),
        Pinot                 ("Apache Pinot"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 751  , null, "PinotDriver"       , "jdbc:pinot://{host}:{port}"  ),
        PipelineDB            ("PipelineDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 675  , null, null                , null                          ),
        PlanetScale           ("PlanetScale"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 839  , null, null                , null                          ),
        PolarDB               ("PolarDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 980  , null, "com.aliyun.polardb.Driver", "jdbc:polardb://{host}:{port:5432}/{database}"),
        PostGIS               ("PostGIS"                                   , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 970  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        PostgreSQL            ("PostgreSQL"                                , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 998  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        PostgresXL            ("Postgres-XL"                               , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 752  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        PouchDB               ("PouchDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 885  , null, null                , null                          ),
        Presto                ("Presto"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 959  , null, "com.facebook.presto.jdbc.PrestoDriver", "jdbc:presto://{host}:{port}/{database}"),
        Prometheus            ("Prometheus"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 943  , null, null                , null                          ),
        Qdrant                ("Qdrant"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 797  , null, null                , null                          ),
        Quasardb              ("Quasardb"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 681  , null, null                , null                          ),
        QuestDB               ("QuestDB"                                   , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 853  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        Raima                 ("Raima Database Manager"                    , DatabaseGenus.None        , KEY_CASE.SRC   , 740  , null, "RDMDriver"         , "jdbc:raima:rdm://{host}:{port:21553}"),
        RapidsDB              ("柏睿数据"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "com.boraydata.jdbc.Driver", "jdbc:rpdsql://{host}:{port}/{database}"),
        RaptorDB              ("RaptorDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 585  , null, null                , null                          ),
        Rasdaman              ("Rasdaman"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 725  , null, null                , null                          ),
        RavenDB               ("RavenDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 901  , null, null                , null                          ),
        RBASE                 ("R:BASE"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 738  , null, null                , null                          ),
        RDF4J                 ("RDF4J"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 779  , null, null                , null                          ),
        RDFox                 ("RDFox"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 708  , null, null                , null                          ),
        Reality               ("Northgate Reality"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 811  , null, null                , null                          ),
        Realm                 ("Realm"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 946  , null, null                , null                          ),
        Redis                 ("Redis"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 992  , null, null                , null                          ),
        Redland               ("Redland"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 737  , null, null                , null                          ),
        RedStore              ("RedStore"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 702  , null, null                , null                          ),
        reldb                 ("reldb"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        ResinCache            ("Resin Cache"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 596  , null, null                , null                          ),
        RethinkDB             ("RethinkDB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 888  , null, null                , null                          ),
        RiakKV                ("Riak KV"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 918  , null, null                , null                          ),
        RiakTS                ("Riak TS"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 687  , null, null                , null                          ),
        RisingWave            ("RisingWave"                                , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 754  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}}"),
        Rizhiyi               ("Rizhiyi"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 584  , null, null                , null                          ),
        RocksDB               ("RocksDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 909  , null, null                , null                          ),
        Rockset               ("Rockset"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 775  , null, null                , null                          ),
        RRDtool               ("RRDtool"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 880  , null, null                , null                          ),
        SadasEngine           ("Sadas Engine"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 614  , null, null                , null                          ),
        SAPIQ                 ("SAP IQ"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 917  , null, "com.sybase.jdbc4.jdbc.SybDriver", "jdbc:sybase:Tds:{host}:{port}/{database}"),
        Scalaris              ("Scalaris"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 748  , null, null                , null                          ),
        ScaleArc              ("ScaleArc"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 755  , null, null                , null                          ),
        SciDB                 ("SciDB"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 766  , null, null                , null                          ),
        ScyllaDB              ("ScyllaDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 934  , null, null                , null                          ),
        SearchBlox            ("SearchBlox"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 723  , null, null                , null                          ),
        searchxml             ("searchxml"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 583  , null, null                , null                          ),
        Sedna                 ("Sedna"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 843  , null, null                , null                          ),
        SelectDB              ("SelectDB"                                  , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 900  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        SenseiDB              ("SenseiDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 643  , null, null                , null                          ),
        Sequoiadb             ("Sequoiadb(巨杉数据库)"                          , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 730  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Siaqodb               ("Siaqodb"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 637  , null, null                , null                          ),
        SingleStore           ("SingleStore"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 927  , null, "com.singlestore.jdbc.Driver", "jdbc:singlestore://{host}:{port}/{database}"),
        SinoDB                ("星瑞格"                                       , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "com.sinodbms.jdbc.IfxDriver", "jdbc:sinodbms-sqli://{host}:{port}/{database}:sinodbmsserver={server}"),
        SiriDB                ("SiriDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 623  , null, null                , null                          ),
        SiteWhere             ("SiteWhere"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 622  , null, null                , null                          ),
        Skytable              ("Skytable"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 663  , null, null                , null                          ),
        SmallSQL              ("SmallSQL"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 599  , null, null                , null                          ),
        Snowflake             ("Snowflake"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 988  , null, "net.snowflake.client.jdbc.SnowflakeDriver", "jdbc:snowflake://{host}"     ),
        solidDB               ("solidDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 803  , null, null                , null                          ),
        Solr                  ("Solr"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 975  , null, null                , null                          ),
        SpaceTime             ("SpaceTime"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 598  , null, null                , null                          ),
        Spark                 ("Spark SQL"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 963  , null, "org.apache.hive.jdbc.HiveDriver", "jdbc:hive2://{host}:{port}/{database}"),
        SparkleDB             ("SparkleDB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 597  , null, null                , null                          ),
        Sparksee              ("Sparksee"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 656  , null, null                , null                          ),
        SpatiaLite            ("SpatiaLite"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 863  , null, null                , null                          ),
        Speedb                ("Speedb"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 680  , null, null                , null                          ),
        Sphinx                ("Sphinx"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 930  , null, null                , null                          ),
        SpliceMachine         ("Splice Machine"                            , DatabaseGenus.None        , KEY_CASE.SRC   , 735  , null, null                , null                          ),
        Splunk                ("Splunk"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 985  , null, null                , null                          ),
        SQLBase               ("SQLBase"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 845  , null, null                , null                          ),
        SQLite                ("SQLite"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 989  , null, "org.sqlite.JDBC"   , "jdbc:sqlite:{database}"      ),
        SQLJS                 ("SQL.JS"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 810  , null, null                , null                          ),
        SQream                ("SQream DB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 773  , null, "com.sqream.jdbc.SQDriver", "jdbc:Sqream://{host}:{port}/{database}"),
        Starcounter           ("Starcounter"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 719  , null, null                , null                          ),
        StarDB                ("京东StarDB"                                  , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 900  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Stardog               ("Stardog"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 866  , null, null                , null                          ),
        StarRocks             ("StarRocks"                                 , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 804  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        StateServer           ("ScaleOut StateServer"                      , DatabaseGenus.None        , KEY_CASE.SRC   , 608  , null, null                , null                          ),
        StellarDB             ("Transwarp StellarDB"                       , DatabaseGenus.None        , KEY_CASE.SRC   , 617  , null, null                , null                          ),
        Strabon               ("Strabon"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 732  , null, null                , null                          ),
        STSdb                 ("STSdb"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 691  , null, null                , null                          ),
        SurrealDB             ("SurrealDB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 793  , null, "com.surrealdb.driver.SyncSurrealDriver", null                          ),
        SwayDB                ("SwayDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 604  , null, null                , null                          ),
        SWCDB                 ("SWC-DB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 606  , null, null                , null                          ),
        Sybase                ("Sybase"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 980  , null, "com.sybase.jdbc4.jdbc.SybDriver", "jdbc:sybase:Tds:{host}:{port}/{database}"),
        Table_Store           ("Alibaba Cloud Table Store"                 , DatabaseGenus.None        , KEY_CASE.SRC   , 669  , null, null                , null                          ),
        Tajo                  ("Tajo"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 698  , null, null                , null                          ),
        Tarantool             ("Tarantool"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 848  , null, null                , null                          ),
        TDengine              ("TDengine"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 882  , "TAOS-RS:,TAOS:", "com.taosdata.jdbc.TSDBDriver", "jdbc:TAOS://{host}:{port:6030}/{database}"),
        TDSQL                 ("TDSQL for MySQL"                           , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 781  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        TensorDB              ("TensorDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        TeraData              ("Teradata"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 979  , null, "com.ncr.teradata.TeraDriver", "jdbc:teradata://{host}/DATABASE={database},DBS_PORT={port:1025}"),
        TerarkDB              ("TerarkDB"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 641  , null, null                , null                          ),
        TerminusDB            ("TerminusDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 662  , null, null                , null                          ),
        Tibero                ("Tibero"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 854  , null, "com.tmax.tibero.jdbc.TbDriver", "jdbc:tibero:thin:@{host}:{port}:{database}"),
        TiDB                  ("TiDB"                                      , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 911  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        TigerGraph            ("TigerGraph"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 851  , null, "com.tigergraph.jdbc.Driver", "jdbc:tg:http://{host}:{port}"),
        Tigris                ("Tigris"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 650  , null, null                , null                          ),
        Timescale             ("TimescaleDB"                               , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 924  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        TimesTen              ("TimesTen"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 837  , null, "com.timesten.jdbc.TimesTenClientDriver", "jdbc:timesten:client:dsn={database}"),
        TinkerGraph           ("TinkerGraph"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 672  , null, null                , null                          ),
        Tkrzw                 ("Tkrzw"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 607  , null, null                , null                          ),
        TokyoTyrant           ("Tokyo Tyrant"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 664  , null, null                , null                          ),
        TomP2P                ("TomP2P"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 639  , null, null                , null                          ),
        Transbase             ("Transbase"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 689  , null, "transbase.jdbc.Driver", "jdbc:transbase://{host}:{port:4444}/{database}"),
        TransLattice          ("TransLattice"                              , DatabaseGenus.None        , KEY_CASE.SRC   , 659  , null, null                , null                          ),
        Trino                 ("Trino"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 928  , null, "io.trino.jdbc.TrinoDriver", "jdbc:trino://{host}:{port}/{database}"),
        TSDB                  ("Alibaba Cloud TSDB"                        , DatabaseGenus.None        , KEY_CASE.SRC   , 642  , null, null                , null                          ),
        TuGraph               ("OceanBase TuGraph"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        TypeDB                ("TypeDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 787  , null, null                , null                          ),
        Typesense             ("Typesense"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 771  , null, null                , null                          ),
        UbiSQL                ("平安科技"                                      , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 900  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Ultipa                ("Ultipa"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 670  , null, null                , null                          ),
        Upscaledb             ("Upscaledb"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 633  , null, null                , null                          ),
        UXDB                  ("优炫数据库"                                     , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "com.uxsino.uxdb.Driver", "jdbc:uxdb://{host}:{port:5432}/{database}"),
        Vald                  ("Vald"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 757  , null, null                , null                          ),
        Valentina             ("Valentina Server"                          , DatabaseGenus.None        , KEY_CASE.SRC   , 676  , null, null                , null                          ),
        Vastbase              ("海量数据"                                      , DatabaseGenus.Postgres    , KEY_CASE.SRC   , 900  , null, "org.postgresql.Driver", "jdbc:postgresql://{host}:{port:5432}/{database}"),
        vearch                ("vearch"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        VelocityDB            ("VelocityDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 648  , null, null                , null                          ),
        Vertica               ("Vertica"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 958  , null, "com.vertica.jdbc.Driver", "jdbc:vertica://{host}:{port:5433}/{database}"),
        Vespa                 ("Vespa"                                     , DatabaseGenus.None        , KEY_CASE.SRC   , 742  , null, null                , null                          ),
        VictoriaMetrics       ("VictoriaMetrics"                           , DatabaseGenus.None        , KEY_CASE.SRC   , 824  , null, null                , null                          ),
        Virtuoso              ("Virtuoso"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 925  , null, null                , null                          ),
        VistaDB               ("VistaDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 749  , null, null                , null                          ),
        Vitess                ("Vitess"                                    , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 812  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        Voldemort             ("Project Voldemort"                         , DatabaseGenus.None        , KEY_CASE.SRC   , 713  , null, null                , null                          ),
        VoltDB                ("VoltDB"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 836  , null, "org.voltdb.jdbc.Driver", "jdbc:voltdb://{host}:{port:21212}"),
        Voracity              ("Voracity"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        WakandaDB             ("WakandaDB"                                 , DatabaseGenus.None        , KEY_CASE.SRC   , 618  , null, null                , null                          ),
        Warp                  ("Warp 10"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 635  , null, null                , null                          ),
        Weaviate              ("Weaviate"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 849  , null, null                , null                          ),
        Xapian                ("Xapian"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 792  , null, null                , null                          ),
        xigemaDB              ("华胜信泰"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 900  , null, "com.informix.jdbc.IfxDriver", "jdbc:informix-sqli://{host}:{port}/{database}:INFORMIXSERVER={server}"),
        XTDB                  ("XTDB"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 645  , null, null                , null                          ),
        XtremeData            ("XtremeData"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 638  , null, null                , null                          ),
        xugu                  ("虚谷"                                        , DatabaseGenus.Oracle      , KEY_CASE.SRC   , 900  , null, "com.xugu.cloudjdbc.Driver", "jdbc:xugu://{host}:{port:5138}/database"),
        YDB                   ("YDB"                                       , DatabaseGenus.None        , KEY_CASE.SRC   , 703  , null, null                , null                          ),
        Yellowbrick           ("Yellowbrick"                               , DatabaseGenus.None        , KEY_CASE.SRC   , 774  , null, null                , null                          ),
        YiDB                  ("天翼数智"                                      , DatabaseGenus.MySQL       , KEY_CASE.SRC   , 900  , null, "com.mysql.jdbc.Driver", "jdbc:mysql://{host}:{port:3306}/{database}"),
        YottaDB               ("YottaDB"                                   , DatabaseGenus.None        , KEY_CASE.SRC   , 682  , null, null                , null                          ),
        YTsaurus              ("YTsaurus"                                  , DatabaseGenus.None        , KEY_CASE.SRC   , 636  , null, null                , null                          ),
        YugabyteDB            ("YugabyteDB"                                , DatabaseGenus.None        , KEY_CASE.SRC   , 896  , null, "com.yugabyte.Driver", "jdbc:yugabytedb://{host}:{port}/{database}"),
        ZeroMQ                ("ZeroMQ"                                    , DatabaseGenus.None        , KEY_CASE.SRC   , 0    , null, null                , null                          ),
        ZODB                  ("ZODB"                                      , DatabaseGenus.None        , KEY_CASE.SRC   , 795  , null, null                , null                          ),

        ;
        DatabaseType(String title, DatabaseGenus genus, KEY_CASE objectNameCase, int boost, String keywords, String driver, String url) {
                this.title = title;
                this.driver = driver;
                this.objectNameCase = objectNameCase;
                this.url = url;
                this.boost = boost;
                if(null != keywords) {
                        String[] ks = keywords.toLowerCase().split(",");
                        for(String k:ks) {
                                this.keywords.add(k.toLowerCase());
                        }
                }
                if(null != url) {
                        //   jdbc:mysql://host:3306/db
                        int idx = url.indexOf(":", 6);
                        if(idx > 0) {
                                this.keywords.add(url.substring(0,idx+1).toLowerCase());
                        }
                }
                if(null != driver) {
                        this.keywords.add(driver.toLowerCase());
                }
        }
        //时查询系统表时对象名(表名、列表)是否大写
        private final List<String> keywords = new ArrayList<>();
        private final KEY_CASE objectNameCase;
        private final int boost;
        private final String title;
        private final String driver;
        private final String url;
        public int boost() {
                return boost;
        }
        public List<String> keywords() {
                return keywords;
        }
        public String driver() {
                return driver;
        }
        public String url() {
                return url;
        }
        public String title() {
                return title;
        }
        public KEY_CASE nameCase() {
                return objectNameCase;
        }

}
